config/routes.rb
TestNestedForms::Application.routes.draw do
  resources :tasks

  resources :projects

  root :to => "projects#index"

end

app/models/project.rb
class Project < ActiveRecord::Base
  has_many :tasks

  accepts_nested_attributes_for :tasks, :reject_if => proc {|attributes| attributes[:name].blank? }, :allow_destroy => true
end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :project
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  # GET /projects
  # GET /projects.xml
  def index
    @projects = Project.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @projects }
    end
  end

  # GET /projects/1
  # GET /projects/1.xml
  def show
    @project = Project.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @project }
    end
  end

  # GET /projects/new
  # GET /projects/new.xml
  def new
    @project = Project.new
    @project.tasks.build
    @project.tasks.build
    @project.tasks.build

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @project }
    end
  end

  # GET /projects/1/edit
  def edit
    @project = Project.find(params[:id])
  end

  # POST /projects
  # POST /projects.xml
  def create
    @project = Project.new(params[:project])

    respond_to do |format|
      if @project.save
        format.html { redirect_to(@project, :notice => 'Project was successfully created.') }
        format.xml  { render :xml => @project, :status => :created, :location => @project }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @project.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /projects/1
  # PUT /projects/1.xml
  def update
    @project = Project.find(params[:id])

    respond_to do |format|
      if @project.update_attributes(params[:project])
        format.html { redirect_to(@project, :notice => 'Project was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @project.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.xml
  def destroy
    @project = Project.find(params[:id])
    @project.destroy

    respond_to do |format|
      format.html { redirect_to(projects_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  # GET /tasks
  # GET /tasks.xml
  def index
    @tasks = Task.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @tasks }
    end
  end

  # GET /tasks/1
  # GET /tasks/1.xml
  def show
    @task = Task.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @task }
    end
  end

  # GET /tasks/new
  # GET /tasks/new.xml
  def new
    @task = Task.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @task }
    end
  end

  # GET /tasks/1/edit
  def edit
    @task = Task.find(params[:id])
  end

  # POST /tasks
  # POST /tasks.xml
  def create
    @task = Task.new(params[:task])

    respond_to do |format|
      if @task.save
        format.html { redirect_to(@task, :notice => 'Task was successfully created.') }
        format.xml  { render :xml => @task, :status => :created, :location => @task }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @task.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /tasks/1
  # PUT /tasks/1.xml
  def update
    @task = Task.find(params[:id])

    respond_to do |format|
      if @task.update_attributes(params[:task])
        format.html { redirect_to(@task, :notice => 'Task was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @task.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.xml
  def destroy
    @task = Task.find(params[:id])
    @task.destroy

    respond_to do |format|
      format.html { redirect_to(tasks_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def link_to_remove_fields(name, f)
    f.hidden_field(:_destroy) + link_to(name, '#', :class => "remove_fields")
  end

  def link_to_add_fields(name, f, association)
    new_object = f.object.class.reflect_on_association(association).klass.new
    hidden_div = content_tag('div', :id => "task_fields_template", :style => "display:none;") do
      f.fields_for(association, new_object, :child_index => "new_#{association}") do |builder|
        render(association.to_s.singularize + "_fields", :f => builder)
      end
    end
    hidden_div + link_to(name, '#', :class => 'add_fields', :'data-association' => association.to_s.singularize)
  end

end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.haml
!!! Strict
%html{ "xml:lang" => "en", :lang => "en", :xmlns => "http://www.w3.org/1999/xhtml" }
  %head
    %title== Test-project #{@page_title}
    %meta{'http-equiv' => "Content-Type", :content => "text/html; charset=utf-8"}
    %link{ :href => "/favicon.ico", :rel => "shortcut icon" }

    = stylesheet_link_tag :all

    = javascript_include_tag 'jquery.min.js', 'rails.js', 'application.js', :cache => 'all_1'

    = csrf_meta_tag

    = yield :local_javascript

    = yield :head
  %body
    #banner
      =image_tag 'your-logo.png'
      .the-title
        %h1
          %p Your application
      #navigation
    #container
      #sidebar
      #contents
        =yield
    #footer
      == &copy; 2010 your company

app/views/projects/_form.html.haml
-if @project.errors.any?
  #error_explanation
    %h2= "#{pluralize(@project.errors.count, "error")} prohibited this project from being saved:"
    %ul
      - @project.errors.full_messages.each do |msg|
        %li= msg

= semantic_form_for @project do |f|
  - f.inputs do
    = f.input :name
    = f.input :description

    %h3 Tasks
    #tasks{:style => 'border:1px solid #ccc; padding: 5px;'}
      = f.semantic_fields_for :tasks do |task|
        = render 'task_fields', :f => task
      .links
        = link_to_add_fields "Add task", f, :tasks
  - f.buttons do
    = f.submit 'Save'

app/views/projects/_task_fields.html.haml
.nested-fields
  = f.inputs do
    = f.input :name
    = f.input :description
    = f.input :done, :as => :boolean
    = link_to_remove_fields "Remove task", f

app/views/projects/edit.html.haml
%h1 Editing project

= render 'form'

= link_to 'Show', @project
\|
= link_to 'Back', projects_path

app/views/projects/index.html.haml
%h1 Listing projects

%table
  %tr
    %th Name
    %th Description
    %th
    %th
    %th

  - @projects.each do |project|
    %tr
      %td= project.name
      %td= project.description
      %td= link_to 'Show', project
      %td= link_to 'Edit', edit_project_path(project)
      %td= link_to 'Destroy', project, :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New Project', new_project_path

app/views/projects/new.html.haml
%h1 New project

= render 'form'



= link_to 'Back', projects_path

app/views/projects/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @project.name
%p
  %b Description:
  = @project.description

%h3 Tasks
%table
  - @project.tasks.each do |task|
    %tr
      %td= task.name
      %td= task.description
      %td= task.done ? "Done" : "Busy"


= link_to 'Edit', edit_project_path(@project)
\|
= link_to 'Back', projects_path

app/views/tasks/_form.html.haml
= form_for @task do |f|
  -if @task.errors.any?
    #error_explanation
      %h2= "#{pluralize(@task.errors.count, "error")} prohibited this task from being saved:"
      %ul
        - @task.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :description
    = f.text_field :description
  .field
    = f.label :status
    = f.text_field :status
  .field
    = f.label :done
    = f.check_box :done
  .field
    = f.label :project_id
    = f.text_field :project_id
  .actions
    = f.submit 'Save'

app/views/tasks/edit.html.haml
%h1 Editing task

= render 'form'

= link_to 'Show', @task
\|
= link_to 'Back', tasks_path

app/views/tasks/index.html.haml
%h1 Listing tasks

%table
  %tr
    %th Name
    %th Description
    %th Status
    %th Done
    %th Project
    %th
    %th
    %th

  - @tasks.each do |task|
    %tr
      %td= task.name
      %td= task.description
      %td= task.status
      %td= task.done
      %td= task.project_id
      %td= link_to 'Show', task
      %td= link_to 'Edit', edit_task_path(task)
      %td= link_to 'Destroy', task, :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New Task', new_task_path

app/views/tasks/new.html.haml
%h1 New task

= render 'form'

= link_to 'Back', tasks_path

app/views/tasks/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @task.name
%p
  %b Description:
  = @task.description
%p
  %b Status:
  = @task.status
%p
  %b Done:
  = @task.done
%p
  %b Project:
  = @task.project_id

= link_to 'Edit', edit_task_path(@task)
\|
= link_to 'Back', tasks_path